In [1]:
import numpy as np

In [2]:
#shape

array1=np.array([[10, 15, 17, 34, 23, 12], [20, 34, 21, 56, 43, 28]])

In [5]:
array1.ravel()

array([10, 15, 17, 34, 23, 12, 20, 34, 21, 56, 43, 28])

In [6]:
array1.reshape(3, 4)

array([[10, 15, 17, 34],
       [23, 12, 20, 34],
       [21, 56, 43, 28]])

In [8]:
array1.resize(2, 6)
print(array1)

[[10 15 17 34 23 12]
 [20 34 21 56 43 28]]


In [11]:
np.hsplit(array1, 3)

[array([[10, 15],
        [20, 34]]),
 array([[17, 34],
        [21, 56]]),
 array([[23, 12],
        [43, 28]])]

In [10]:
a1 = np.array([10, 15, 17, 34, 23, 12])
a2 = np.array([20, 34, 21, 56, 43, 28])
np.hstack([a1, a2])

array([10, 15, 17, 34, 23, 12, 20, 34, 21, 56, 43, 28])

In [12]:
#demo numpy

In [14]:
n1=np.array([1,2,3,4])
n1

array([1, 2, 3, 4])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [17]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.empty(2)

array([ 1.24040885e+165, -4.31411512e+183])

In [19]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.linspace(1,7,5)

array([1. , 2.5, 4. , 5.5, 7. ])

In [25]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])